name: pretty_charts
description: "A Flutter library to draw pretty charts like Matplotlib or Plotly"
version: 0.0.1-dev.1
homepage: https://github.com/ClementBeal/pretty_charts
repository: https://github.com/ClementBeal/pretty_charts
issue_tracker: https://github.com/ClementBeal/pretty_charts/issues

topics:
  - chart
  - plot
  - scientist
  - graph
  - visualization

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
